name: CI Pipeline

on:
  push:
    branches: [develop, main, feature/*]
  pull_request:
    branches: [main, develop]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ' 3.27.3'

      # Installation des dépendances du projet Flutter
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./buildtrack_app

      # Exécution de l'analyse statique du code
      - name: Analyze
        run: flutter analyze
        working-directory: ./buildtrack_app

      # Exécution des tests unitaires et d'intégration
      - name: Run tests
        run: flutter test
        working-directory: ./buildtrack_app

      # Génération de l'APK en mode debug
      - name: Build APK (Debug)
        run: flutter build apk --debug
        working-directory: ./buildtrack_app

      # Vérification de la génération de l'APK
      - name: Verify Build
        run: |
          if [ -f "build/app/outputs/flutter-apk/app-debug.apk" ]; then
            echo "✅ Build successful"
          else
            echo "❌ Build failed"
            exit 1
          fi
        working-directory: ./buildtrack_app
