name: CI Test Simple

on:
  push:
    branches: [feature/test-flavors-pipeline]
  pull_request:

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test Flutter
        run: |
          echo "ðŸ“¦ Installation Flutter..."
          git clone https://github.com/flutter/flutter.git -b stable
          export PATH="$PWD/flutter/bin:$PATH"
          flutter --version
        working-directory: ./buildtrack_app
